### ISSUE TITLE
Minicart Fails to Update After Buying a Product

### ISSUE THREAD

**Issue by StefanBossbaly** [litecommerce/core#19]
A short while after installation, when clicking the "Add to Bag" button the product in not added to the minicart in the top right corner. However a message is displayed at the top of the webpage saying "Product has been added to the cart". When navigating to the store/cart sub directory it says "Your shopping bag is empty". My store is set up here http://www.nzymclothing.com/ . Here is the log ...

```
[info, Dec 28 2011 20:35:54] Marketplace [check_for_updates]: the "http://www.litecommerce.com/?q=api/check_for_updates" URL requested
[info, Dec 28 2011 20:35:54] Marketplace [check_for_updates]: valid response received
[info, Dec 28 2011 20:36:00] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 28 2011 20:36:00] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 28 2011 20:36:00] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 28 2011 20:36:00] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 28 2011 20:39:11] Marketplace [get_addons]: the "http://www.litecommerce.com/?q=api/get_addons" URL requested
[info, Dec 28 2011 20:39:11] Marketplace [get_addons]: valid response received
[info, Dec 28 2011 20:40:20] Marketplace [get_addon_info]: the "http://www.litecommerce.com/?q=api/get_addon_info" URL requested
[info, Dec 28 2011 20:40:20] Marketplace [get_addon_info]: valid response received
[info, Dec 28 2011 20:40:20] Marketplace [get_cores]: the "http://www.litecommerce.com/?q=api/get_cores" URL requested
[info, Dec 28 2011 20:40:20] Marketplace [get_cores]: valid response received
[info, Dec 28 2011 20:40:23] Marketplace [get_addon_pack]: the "http://www.litecommerce.com/?q=api/get_addon_pack" URL requested
[info, Dec 28 2011 20:40:23] Module pack ("CDev\PaypalWPS") is received: "/home/stefan/public_html/drupal/modules/lc_connector/litecommerce/var/tmp/4efbd3176439f.gz"
[info, Dec 28 2011 20:40:23] Marketplace [get_addon_hash]: the "http://www.litecommerce.com/?q=api/get_addon_hash" URL requested
[info, Dec 28 2011 20:40:23] Marketplace [get_addon_hash]: valid response received
[info, Dec 28 2011 20:40:23] Entry "CDev\PaypalWPS" archive is unpacked: "/home/stefan/public_html/drupal/modules/lc_connector/litecommerce/var/tmp/4efbd3176439f"
[info, Dec 28 2011 20:40:24] File is added: "skins/admin/en/modules/CDev/PaypalWPS/config.tpl"
[info, Dec 28 2011 20:40:24] File is added: "classes/XLite/Module/CDev/PaypalWPS/install.yaml"
[info, Dec 28 2011 20:40:24] File is added: "classes/XLite/Module/CDev/PaypalWPS/Main.php"
[info, Dec 28 2011 20:40:24] File is added: "classes/XLite/Module/CDev/PaypalWPS/icon.png"
[info, Dec 28 2011 20:40:24] File is added: "classes/XLite/Module/CDev/PaypalWPS/Model/Payment/Processor/PaypalWPS.php"
[info, Dec 28 2011 20:40:24] Module has been successfully installed
[info, Dec 28 2011 20:40:35] Marketplace [check_for_updates]: the "http://www.litecommerce.com/?q=api/check_for_updates" URL requested
[info, Dec 28 2011 20:40:35] Marketplace [check_for_updates]: valid response received
[info, Dec 28 2011 20:40:35] Marketplace [get_cores]: the "http://www.litecommerce.com/?q=api/get_cores" URL requested
[info, Dec 28 2011 20:40:35] Marketplace [get_cores]: valid response received
[info, Dec 28 2011 20:40:35] Marketplace [get_addons]: the "http://www.litecommerce.com/?q=api/get_addons" URL requested
[info, Dec 28 2011 20:40:35] Marketplace [get_addons]: valid response received
[info, Dec 28 2011 20:45:50] Marketplace [get_addon_info]: the "http://www.litecommerce.com/?q=api/get_addon_info" URL requested
[info, Dec 28 2011 20:45:50] Marketplace [get_addon_info]: valid response received
[info, Dec 28 2011 20:45:52] Marketplace [get_addon_pack]: the "http://www.litecommerce.com/?q=api/get_addon_pack" URL requested
[info, Dec 28 2011 20:45:53] Module pack ("CDev\GoogleAnalytics") is received: "/home/stefan/public_html/drupal/modules/lc_connector/litecommerce/var/tmp/4efbd46138d94.gz"
[info, Dec 28 2011 20:45:53] Marketplace [get_addon_hash]: the "http://www.litecommerce.com/?q=api/get_addon_hash" URL requested
[info, Dec 28 2011 20:45:53] Marketplace [get_addon_hash]: valid response received
[info, Dec 28 2011 20:45:53] Entry "CDev\GoogleAnalytics" archive is unpacked: "/home/stefan/public_html/drupal/modules/lc_connector/litecommerce/var/tmp/4efbd46138d94"
[info, Dec 28 2011 20:45:54] File is added: "skins/default/en/modules/CDev/GoogleAnalytics/drupal.js"
[info, Dec 28 2011 20:45:54] File is added: "skins/default/en/modules/CDev/GoogleAnalytics/header.tpl"
[info, Dec 28 2011 20:45:54] File is added: "skins/default/en/modules/CDev/GoogleAnalytics/drupal.tpl"
[info, Dec 28 2011 20:45:54] File is added: "skins/admin/en/modules/CDev/GoogleAnalytics/header.tpl"
[info, Dec 28 2011 20:45:54] File is added: "classes/XLite/Module/CDev/GoogleAnalytics/upgrade/1.0/3/post_rebuild.php"
[info, Dec 28 2011 20:45:54] File is added: "classes/XLite/Module/CDev/GoogleAnalytics/install.yaml"
[info, Dec 28 2011 20:45:54] File is added: "classes/XLite/Module/CDev/GoogleAnalytics/Main.php"
[info, Dec 28 2011 20:45:54] File is added: "classes/XLite/Module/CDev/GoogleAnalytics/icon.png"
[info, Dec 28 2011 20:45:54] File is added: "classes/XLite/Module/CDev/GoogleAnalytics/View/CheckoutSuccess.php"
[info, Dec 28 2011 20:45:54] File is added: "classes/XLite/Module/CDev/GoogleAnalytics/View/AView.php"
[info, Dec 28 2011 20:45:54] File is added: "classes/XLite/Module/CDev/GoogleAnalytics/View/Header.php"
[info, Dec 28 2011 20:45:54] File is added: "classes/XLite/Module/CDev/GoogleAnalytics/View/FormField/Select/TrackingType.php"
[info, Dec 28 2011 20:45:54] File is added: "classes/XLite/Module/CDev/GoogleAnalytics/LICENSE.txt"
[info, Dec 28 2011 20:45:54] Module has been successfully installed
[info, Dec 28 2011 20:46:04] Marketplace [check_for_updates]: the "http://www.litecommerce.com/?q=api/check_for_updates" URL requested
[info, Dec 28 2011 20:46:04] Marketplace [check_for_updates]: valid response received
[info, Dec 28 2011 20:46:05] Marketplace [get_cores]: the "http://www.litecommerce.com/?q=api/get_cores" URL requested
[info, Dec 28 2011 20:46:05] Marketplace [get_cores]: valid response received
[info, Dec 28 2011 20:46:05] Marketplace [get_addons]: the "http://www.litecommerce.com/?q=api/get_addons" URL requested
[info, Dec 28 2011 20:46:05] Marketplace [get_addons]: valid response received
[info, Dec 28 2011 20:51:12] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 28 2011 20:51:12] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 28 2011 20:51:12] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 28 2011 20:51:12] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 28 2011 20:55:58] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 28 2011 20:55:58] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 28 2011 20:55:58] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 28 2011 20:55:58] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 28 2011 21:01:42] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 28 2011 21:01:42] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 28 2011 21:01:42] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 28 2011 21:01:42] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 28 2011 21:02:09] Marketplace [get_addon_info]: the "http://www.litecommerce.com/?q=api/get_addon_info" URL requested
[info, Dec 28 2011 21:02:09] Marketplace [get_addon_info]: valid response received
[info, Dec 28 2011 21:02:14] Marketplace [get_addon_pack]: the "http://www.litecommerce.com/?q=api/get_addon_pack" URL requested
[info, Dec 28 2011 21:02:15] Module pack ("CDev\USPS") is received: "/home/stefan/public_html/drupal/modules/lc_connector/litecommerce/var/tmp/4efbd8370dfb8.gz"
[info, Dec 28 2011 21:02:15] Marketplace [get_addon_hash]: the "http://www.litecommerce.com/?q=api/get_addon_hash" URL requested
[info, Dec 28 2011 21:02:15] Marketplace [get_addon_hash]: valid response received
[info, Dec 28 2011 21:02:15] Entry "CDev\USPS" archive is unpacked: "/home/stefan/public_html/drupal/modules/lc_connector/litecommerce/var/tmp/4efbd8370dfb8"
[info, Dec 28 2011 21:02:16] File is added: "skins/admin/en/modules/CDev/USPS/test.tpl"
[info, Dec 28 2011 21:02:16] File is added: "skins/admin/en/modules/CDev/USPS/config.tpl"
[info, Dec 28 2011 21:02:16] File is added: "skins/admin/en/modules/CDev/USPS/main.tpl"
[info, Dec 28 2011 21:02:16] File is added: "skins/admin/en/modules/CDev/USPS/location.tpl"
[info, Dec 28 2011 21:02:16] File is added: "classes/XLite/Module/CDev/USPS/install.yaml"
[info, Dec 28 2011 21:02:16] File is added: "classes/XLite/Module/CDev/USPS/Main.php"
[info, Dec 28 2011 21:02:16] File is added: "classes/XLite/Module/CDev/USPS/icon.png"
[info, Dec 28 2011 21:02:16] File is added: "classes/XLite/Module/CDev/USPS/View/Tabs/ShippingSettings.php"
[info, Dec 28 2011 21:02:16] File is added: "classes/XLite/Module/CDev/USPS/View/TopMenu.php"
[info, Dec 28 2011 21:02:16] File is added: "classes/XLite/Module/CDev/USPS/README"
[info, Dec 28 2011 21:02:16] File is added: "classes/XLite/Module/CDev/USPS/Controller/Admin/Usps.php"
[info, Dec 28 2011 21:02:16] File is added: "classes/XLite/Module/CDev/USPS/Model/Shipping/Processor/USPS.php"
[info, Dec 28 2011 21:02:16] Module has been successfully installed
[info, Dec 28 2011 21:02:25] Marketplace [check_for_updates]: the "http://www.litecommerce.com/?q=api/check_for_updates" URL requested
[info, Dec 28 2011 21:02:26] Marketplace [check_for_updates]: valid response received
[info, Dec 28 2011 21:02:26] Marketplace [get_cores]: the "http://www.litecommerce.com/?q=api/get_cores" URL requested
[info, Dec 28 2011 21:02:26] Marketplace [get_cores]: valid response received
[info, Dec 28 2011 21:02:26] Marketplace [get_addons]: the "http://www.litecommerce.com/?q=api/get_addons" URL requested
[info, Dec 28 2011 21:02:26] Marketplace [get_addons]: valid response received
[info, Dec 28 2011 22:20:24] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 28 2011 22:20:25] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 28 2011 22:20:25] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 28 2011 22:20:25] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 28 2011 22:49:50] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 28 2011 22:49:50] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 28 2011 22:49:50] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 28 2011 22:49:50] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 28 2011 22:57:32] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 28 2011 22:57:33] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 28 2011 22:57:33] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 28 2011 22:57:33] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 28 2011 22:58:56] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 28 2011 22:58:56] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 28 2011 22:58:56] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 28 2011 22:58:56] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 28 2011 22:59:36] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 28 2011 22:59:36] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 28 2011 22:59:36] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 28 2011 22:59:37] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 28 2011 23:00:19] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 28 2011 23:00:19] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 28 2011 23:00:19] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 28 2011 23:00:19] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 28 2011 23:00:29] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 28 2011 23:00:29] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 28 2011 23:00:29] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 28 2011 23:00:30] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 28 2011 23:03:46] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 28 2011 23:03:46] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 28 2011 23:03:46] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 28 2011 23:03:46] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 29 2011 10:00:15] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 29 2011 10:00:16] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 29 2011 10:00:16] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 29 2011 10:00:16] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 29 2011 10:14:38] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 29 2011 10:14:38] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 29 2011 10:14:38] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 29 2011 10:14:38] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 29 2011 10:21:00] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 29 2011 10:21:00] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 29 2011 10:21:00] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 29 2011 10:21:00] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 29 2011 11:28:05] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 29 2011 11:28:05] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 29 2011 11:28:05] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 29 2011 11:28:05] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 29 2011 11:39:28] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 29 2011 11:39:28] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 29 2011 11:39:28] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 29 2011 11:39:28] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 29 2011 12:09:28] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 29 2011 12:09:28] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 29 2011 12:09:28] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 29 2011 12:09:29] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 29 2011 12:10:32] The module "CDev\GoogleAnalytics" has been uninstalled successfully
[info, Dec 29 2011 12:10:32] Marketplace [get_addons]: the "http://www.litecommerce.com/?q=api/get_addons" URL requested
[info, Dec 29 2011 12:10:32] Marketplace [get_addons]: valid response received
[info, Dec 29 2011 12:15:13] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 29 2011 12:15:13] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 29 2011 12:15:13] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 29 2011 12:15:13] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 29 2011 12:15:18] Marketplace [get_cores]: the "http://www.litecommerce.com/?q=api/get_cores" URL requested
[info, Dec 29 2011 12:15:19] Marketplace [get_cores]: valid response received
[info, Dec 29 2011 12:16:44] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 29 2011 12:16:44] Marketplace [get_hosting_score]: response has an invalid format
[info, Dec 29 2011 12:16:44] Marketplace [get_hosting_score]: the "http://www.litecommerce.com/?q=api/get_hosting_score" URL requested
[error, Dec 29 2011 12:16:45] Marketplace [get_hosting_score]: response has an invalid format
```

**Comment by StefanBossbaly** [comment]
I restored the database from an older version and it seems to work now. I can upload the "bad database" if you would like.

**Comment by maxmukhin** [comment]
Could you please provide us with the other logs ? "upgrade.log" is for the upgrade process only.

**Comment by qimmik** [comment]
Seems like he changed from using LC3... I don't see why he would change from using LC3 cause it is great, but looking at the site he posted, it's not lc3.

**Comment by StefanBossbaly** [comment]
Sorry I put a .htaccess to redirect to the new folder and yes the new site is not LC3. Where is the log folder? I will upload some more.

**Comment by maxmukhin** [comment]
{drupal_catalog}/modules/lc_connector/litecommerce/var/log/ 

or just 

{litecommerce_catalog}/var/log   if you have installed stand-alone LC installation.

**Comment by ghost** [comment]
I'm also having this problem.  It's bizarre, because it worked when I first installed it.  Then because a lot of others things stopped working while I was playing around, I did a completely clean install with a new database.  The minicart still doesn't update.

xlite.log is blank

php_errors.log:

[11-Apr-2012 02:05:07] Error (code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '57-XLiteViewItemsListModuleManage' for key 'iname'
Server API: cgi-fcgi;
Request method: GET;
URI: /modules/lc_connector/litecommerce/admin.php?target=addons_list_installed;
Backtrace: 
#0 /home/magicbir/public_html/modules/lc_connector/litecommerce/lib/Doctrine/ORM/Persisters/BasicEntityPersister.php(236): XLite\Core\Statement->execute()
#1 /home/magicbir/public_html/modules/lc_connector/litecommerce/lib/Doctrine/ORM/UnitOfWork.php(708): Doctrine\ORM\Persisters\BasicEntityPersister->executeInserts()
#2 /home/magicbir/public_html/modules/lc_connector/litecommerce/lib/Doctrine/ORM/UnitOfWork.php(287): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#3 /home/magicbir/public_html/modules/lc_connector/litecommerce/lib/Doctrine/ORM/EntityManager.php(334): Doctrine\ORM\UnitOfWork->commit()
#4 /home/magicbir/public_html/modules/lc_connector/litecommerce/var/run/classes/XLite/Model/Repo/ARepo.php(463): Doctrine\ORM\EntityManager->flush()
#5 /home/magicbir/public_html/modules/lc_connector/litecommerce/var/run/classes/XLite/Model/Repo/ARepo.php(483): XLite\Model\Repo\ARepo->flushChanges()
#6 /home/magicbir/public_html/modules/lc_connector/litecommerce/var/run/classes/XLite/Model/Repo/SessionCell.php(60): XLite\Model\Repo\ARepo->insert(Array)
#7 /home/magicbir/public_html/modules/lc_connector/litecommerce/var/run/classes/XLite/Model/Session.php(237): XLite\Model\Repo\SessionCell->insertCell(57, 'XLiteViewItemsL...', Array)
#8 /home/magicbir/public_html/modules/lc_connector/litecommerce/var/run/classes/XLite/Model/Session.php(165): XLite\Model\Session->setCellValue('XLiteViewItemsL...', Array)
#9 /home/magicbir/public_html/modules/lc_connector/litecommerce/var/run/classes/XLite/Core/SessionAbstract.php(120): XLite\Model\Session->__set('XLiteViewItemsL...', Array)
#10 /home/magicbir/public_html/modules/lc_connector/litecommerce/var/run/classes/XLite/Core/SessionAbstract.php(179): XLite\Core\SessionAbstract->__set('XLiteViewItemsL...', Array)
#11 /home/magicbir/public_html/modules/lc_connector/litecommerce/var/run/classes/XLite/View/RequestHandler/ARequestHandler.php(231): XLite\Core\SessionAbstract->set('XLiteViewItemsL...', Array)
#12 /home/magicbir/public_html/modules/lc_connector/litecommerce/var/run/classes/XLite/View/AViewAbstract.php(259): XLite\View\RequestHandler\ARequestHandler->initView()
#13 /home/magicbir/public_html/modules/lc_connector/litecommerce/var/run/skins/admin/en/modules_manager/manage/body.tpl.php(6): XLite\View\AViewAbstract->display()
#14 /home/magicbir/public_html/modules/lc_connector/litecommerce/var/run/classes/XLite/View/AViewAbstract.php(285): include('/home/magicbir/...')
#15 /home/magicbir/public_html/modules/lc_connector/litecommerce/var/run/skins/admin/en/common/dialog.tpl.php(4): XLite\View\AViewAbstract->display('modules_manager...')
#16 /home/magicbir/public_html/modules/lc_connector/litecommerce/var/run/classes/XLite/View/AViewAbstract.php(285): include('/home/magicbir/...')
#17 /home/magicbir/public_html/modules/lc_connector/litecommerce/var/run/classes/XLite/View/AViewAbstract.php(921): XLite\View\AViewAbstract->display()
#18 /home/magicbir/public_html/modules/lc_connector/litecommerce/var/run/skins/admin/en/center.tpl.php(61): XLite\View\AViewAbstract->displayViewListContent('admin.center')
#19 /home/magicbir/public_html/modules/lc_connector/litecommerce/var/run/classes/XLite/View/AViewAbstract.php(285): include('/home/magicbir/...')
#20 /home/magicbir/public_html/modules/lc_connector/litecommerce/var/run/classes/XLite/View/Content.php(54): XLite\View\AViewAbstract->display('center.tpl')
#21 /home/magicbir/public_html/modules/lc_connector/litecommerce/var/run/skins/admin/en/main.tpl.php(13): XLite\View\Content->display('center.tpl')
#22 /home/magicbir/public_html/modules/lc_connector/litecommerce/var/run/classes/XLite/View/AViewAbstract.php(285): include('/home/magicbir/...')
#23 /home/magicbir/public_html/modules/lc_connector/litecommerce/var/run/classes/XLite/View/Content.php(54): XLite\View\AViewAbstract->display(NULL)
#24 /home/magicbir/public_html/modules/lc_connector/litecommerce/var/run/classes/XLite/View/AViewAbstract.php(315): XLite\View\Content->display()
#25 /home/magicbir/public_html/modules/lc_connector/litecommerce/var/run/classes/XLite/View/Controller.php(272): XLite\View\AViewAbstract->getContent()
#26 /home/magicbir/public_html/modules/lc_connector/litecommerce/var/run/classes/XLite/View/Controller.php(308): XLite\View\Controller->prepareContent()
#27 /home/magicbir/public_html/modules/lc_connector/litecommerce/var/run/classes/XLite/View/Controller.php(97): XLite\View\Controller->displayPage(NULL)
#28 /home/magicbir/public_html/modules/lc_connector/litecommerce/var/run/classes/XLite/Controller/AControllerAbstract.php(377): XLite\View\Controller->display()
#29 /home/magicbir/public_html/modules/lc_connector/litecommerce/var/run/classes/XLite.php(340): XLite\Controller\AControllerAbstract->processRequest()
#30 /home/magicbir/public_html/modules/lc_connector/litecommerce/admin.php(30): XLite->processRequest()
#31 {main}

**Comment by maxmukhin** [comment]
@sgpark :

Could you please check that the http_host details are as the same as request URL (URL that you are using in your browser). Otherwise you should post a support issue ticket to http://bt.litecommerce.com - we will check the issue on your LC installation directly.
